{% set name = "dbt-redshift" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dbt-redshift-{{ version }}.tar.gz
  sha256: c2fecf6b326a9977d79cc3b1aa79cdc8f599abf55b990b730410f9adf866e1b6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    # Ref: <https://www.marcelotrevisani.com/grayskull>
    - boto3 >=1.4.4,<2.0.0
    - dbt-core >=1.2.0,<1.3  # Changed ==1.1.* to <1.2
    - dbt-postgres >=1.2.0,<1.3  # Changed ==1.1.* to <1.2
    - python >=3.7

test:
  imports:
    - dbt
    - dbt.adapters
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dbt-labs/dbt-redshift
  summary: The Redshift adapter plugin for dbt
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - maresb
    - thewchan
